version: '3'
 
services:
    reverseproxy:
        container_name: reverse_proxy
        image: nginx
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 6379:6379
        restart: always
    redis1:
        container_name: docker-redis1
        depends_on:
            - reverseproxy
        image: 'bitnami/redis:latest'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
    redis2:
        container_name: docker-redis2
        depends_on:
            - reverseproxy
        image: 'bitnami/redis:latest'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes

